package common;

public enum MessageType {
    LOGIN,
    LOGIN_OK,
    LOGIN_FAIL,
    FIND_GAME,
    CANCEL_FIND_GAME,
    GAME_START,
    MOVE,MOVE_OK,MOVE_INVALID,
    CHECKMATE, DRAW , RESIGN,
    DRAW_OFFER,DRAW_ACCEPT,DRAW_DELCINE,
    CHAT,
    HISTORY_REQUEST, HISTORY_RESPONSE,
    STATS_REQUEST, STATS_RESPONSE,
    OPPONENT_DISCONNECTED, ERROR,
    PROMOTE_REQUEST, PROMOTE_RESPONSE,
}
